name: Docker CI/CD Pipeline

on:
  push:
    branches: [ "main", "mfe-updates" ] # Now runs on your branch too
  pull_request:
    branches: [ "main" ] # Runs when you open a PR to check if code is good

env:
  REGISTRY: ghcr.io
  # We manually set this to lowercase to avoid Docker's naming error
  IMAGE_NAME: ${{ github.repository_owner }}/elec4docker

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install & Test
        run: |
          npm ci
          npm test --if-present

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./ops/app.Dockerfile
          # We only want to 'push' the image to the registry if we are on the main branch
          # This prevents experimental branch code from overwriting your 'latest' production image
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
